# PowerControllerViewer production configuration file for Sydney

Website:
  HostingIP: 127.0.0.1
  Port: 8000
  PageAutoRefresh: 200
  DebugMode: False

Files:
  LogfileName: logs/logfile.log
  # Include the process ID in the log entries
  LogProcessID: True
  LogfileMaxLines: 2500
  # How much information do we write to the log file. One of: none; error; warning; summary; detailed; debug; all
  LogfileVerbosity: detailed
  # How much information do we write to the console. One of: error; warning; summary; detailed; debug; all
  ConsoleVerbosity: detailed